-- Run this file in Supabase Dashboard > SQL Editor.
-- It stores the existing AssistanceRecord JSON unchanged while adding secure,
-- indexed fields for identity, duplicates, timestamps, and realtime updates.

create table if not exists public.assistance_records (
  id bigint generated by default as identity primary key,
  record jsonb not null default '{}'::jsonb,
  surname_normalized text not null,
  first_name_normalized text not null,
  birthday date not null,
  created_by uuid not null default auth.uid() references auth.users(id),
  updated_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Repeat applications are valid. This non-unique index makes history lookup
-- fast without treating another application from the same applicant as an error.
drop index if exists public.assistance_records_applicant_identity_idx;
create index if not exists assistance_records_applicant_history_idx
  on public.assistance_records (surname_normalized, first_name_normalized, birthday);

create index if not exists assistance_records_created_at_idx
  on public.assistance_records (created_at desc);

-- The records desk, filters, matching, and reports need application metadata,
-- but not the large front/back image data. This security-invoker view removes
-- images before the response leaves Supabase. A complete row is fetched only
-- when staff opens or edits an application.
create or replace view public.assistance_record_summaries
with (security_invoker = true)
as
select
  id,
  record - 'idImage' - 'idImageBack' as record,
  surname_normalized,
  first_name_normalized,
  birthday,
  created_at,
  updated_at
from public.assistance_records;

alter table public.assistance_records enable row level security;

revoke all on public.assistance_records from anon;
grant select, insert, update, delete on public.assistance_records to authenticated;
grant usage, select on sequence public.assistance_records_id_seq to authenticated;
grant select on public.assistance_record_summaries to authenticated;

drop policy if exists "Authenticated staff can read shared records" on public.assistance_records;
create policy "Authenticated staff can read shared records"
  on public.assistance_records
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated staff can create shared records" on public.assistance_records;
create policy "Authenticated staff can create shared records"
  on public.assistance_records
  for insert
  to authenticated
  with check ((select auth.uid()) = created_by and (select auth.uid()) = updated_by);

drop policy if exists "Authenticated staff can update shared records" on public.assistance_records;
create policy "Authenticated staff can update shared records"
  on public.assistance_records
  for update
  to authenticated
  using (true)
  with check ((select auth.uid()) = updated_by);

drop policy if exists "Authenticated staff can delete shared records" on public.assistance_records;
create policy "Authenticated staff can delete shared records"
  on public.assistance_records
  for delete
  to authenticated
  using (true);

create or replace function public.set_assistance_record_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists assistance_records_set_updated_at on public.assistance_records;
create trigger assistance_records_set_updated_at
  before update on public.assistance_records
  for each row execute function public.set_assistance_record_updated_at();

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'assistance_records'
  ) then
    alter publication supabase_realtime add table public.assistance_records;
  end if;
end
$$;
